function Hd = firfilter_impulseresponse
%FIRFILTER_IMPULSERESPONSE Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 8.1 and the DSP System Toolbox 8.4.
% Generated on: 25-Sep-2016 17:16:36

Fpass = 2500000;   % Passband Frequency
Fstop = 4500000;   % Stopband Frequency
Apass = 1;         % Passband Ripple (dB)
Astop = 60;        % Stopband Attenuation (dB)
Fs    = 10000000;  % Sampling Frequency

h = fdesign.lowpass('fp,fst,ap,ast', Fpass, Fstop, Apass, Astop, Fs);

Hd = design(h, 'equiripple', ...
    'MinOrder', 'any', ...
    'StopbandShape', 'flat');
impz(Hd);
%axis([1 75 -0.2 0.35])



